### ISSUE TITLE
Any plan to update to finagle-http_2.11-6.33.0, any new 2.x elastic lib?

### ISSUE THREAD

**Issue by picoflow1** [rore/finagle-es-proxy#1]
Enjoy learning from the code. I update to finagle-http_2.11-6.33.0, finagle API changed. Cannot compile. Look at source, many API restricts previously working API. Any plan to update it?

**Comment by rore** [comment]
This was mainly a demo project so I don't think I'll get to upgrade it soon. 
If you happen to do that I'll be happy to merge in a pull request.
